apiVersion: v1
kind: Service
metadata:
  name: mongodb-0
  labels:
    app: mongodb-0
spec:
  clusterIP: None
  selector:
    app: mongodb-0
  ports:
    - port: 27017
      targetPort: 27017
