apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-lb
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: python-app  
#    app: python-flask-app  

